name: Merge Notification

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Slack notification
      run: |
        curl -d '{"text": "${{ github.author }} just merged ${{ github.head_ref }}!"}' -H "Content-Type: application/json" -X POST ${{secrets.SLACK_WEBHOOK}}
