name: Merge Notifications

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack notification
      run: |
        curl -d '{"text": "${{ github.author }} released ${{ github.ref }}!"}' -H "Content-Type: application/json" -X POST ${{secrets.SLACK_WEBHOOK}}
