name: Merge Notification

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Slack notification
      if: github.event.pull_request.merged == true
      run: |
        curl -d '{"text": "${{ github.event.pull_request.user.login }} just merged ${{ github.event.pull_request.title }} (${{ github.head_ref }}) into ${{ github.event.pull_request.base.repo.name }}!"}' -H "Content-Type: application/json" -X POST ${{secrets.SLACK_WEBHOOK}}
